"""create decision evidence table

Revision ID: 00d0041de8d2
Revises: bf784b98137f
Create Date: 2026-08-27 23:20:00.189946

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00d0041de8d2"
down_revision: Union[str, Sequence[str], None] = "bf784b98137f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_alternative_id", sa.Uuid(), nullable=False),
        sa.Column("document_chunk_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=20), nullable=False),
        sa.Column("relevance_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evidence_type IN ('supporting', 'opposing')",
            name="ck_decision_evidence_type",
        ),
        sa.ForeignKeyConstraint(
            ["decision_alternative_id"],
            ["decision_alternatives.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_chunk_id"], ["document_chunks.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "decision_alternative_id",
            "document_chunk_id",
            name="uq_decision_evidence_alternative_chunk",
        ),
    )
    op.create_index(
        op.f("ix_decision_evidence_decision_alternative_id"),
        "decision_evidence",
        ["decision_alternative_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_evidence_document_chunk_id"),
        "decision_evidence",
        ["document_chunk_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_decision_evidence_document_chunk_id"), table_name="decision_evidence"
    )
    op.drop_index(
        op.f("ix_decision_evidence_decision_alternative_id"),
        table_name="decision_evidence",
    )
    op.drop_table("decision_evidence")
    # ### end Alembic commands ###
