"""add decision record attribution

Revision ID: 06d355ec93d0
Revises: 940b0fb71c87
Create Date: 2026-09-28 00:30:45.768494

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06d355ec93d0"
down_revision: Union[str, Sequence[str], None] = "940b0fb71c87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "decisions", sa.Column("created_by_user_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "decisions", sa.Column("decided_by_user_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_decisions_created_by_user_id"),
        "decisions",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decisions_decided_by_user_id"),
        "decisions",
        ["decided_by_user_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_decisions_created_by_user_id_users",
        "decisions",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_decisions_decided_by_user_id_users",
        "decisions",
        "users",
        ["decided_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_decisions_decided_by_user_id_users", "decisions", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_decisions_created_by_user_id_users", "decisions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_decisions_decided_by_user_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_created_by_user_id"), table_name="decisions")
    op.drop_column("decisions", "decided_by_user_id")
    op.drop_column("decisions", "created_by_user_id")
    # ### end Alembic commands ###
