"""create rate limit buckets table

Revision ID: 0bbb364975d6
Revises: 20e85b30010b
Create Date: 2026-09-15 22:59:41.608324

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bbb364975d6"
down_revision: Union[str, Sequence[str], None] = "20e85b30010b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_buckets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=100), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_count", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "key_hash ~ '^[0-9a-f]{64}$'", name="ck_rate_limit_buckets_key_hash_format"
        ),
        sa.CheckConstraint(
            "length(scope) > 0", name="ck_rate_limit_buckets_scope_not_empty"
        ),
        sa.CheckConstraint(
            "request_count >= 1", name="ck_rate_limit_buckets_positive_request_count"
        ),
        sa.CheckConstraint(
            "window_expires_at > window_started_at",
            name="ck_rate_limit_buckets_valid_window",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scope", "key_hash", name="uq_rate_limit_buckets_scope_key_hash"
        ),
    )
    op.create_index(
        op.f("ix_rate_limit_buckets_window_expires_at"),
        "rate_limit_buckets",
        ["window_expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rate_limit_buckets_window_expires_at"), table_name="rate_limit_buckets"
    )
    op.drop_table("rate_limit_buckets")
    # ### end Alembic commands ###
