"""prevent duplicate document versions

Revision ID: 1aee65169b74
Revises: cb30cfd42e5e
Create Date: 2026-08-22 07:16:24.913080

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1aee65169b74"
down_revision: Union[str, Sequence[str], None] = "cb30cfd42e5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_document_versions_document_id_checksum_sha256",
        "document_versions",
        ["document_id", "checksum_sha256"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_document_versions_document_id_checksum_sha256",
        "document_versions",
        type_="unique",
    )
    # ### end Alembic commands ###
