"""create user email verification tokens table

Revision ID: 20e85b30010b
Revises: 7a595c22ee85
Create Date: 2026-09-07 09:19:02.423041

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20e85b30010b"
down_revision: Union[str, Sequence[str], None] = "7a595c22ee85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_email_verification_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "token_hash ~ '^[0-9a-f]{64}$'",
            name="ck_user_email_verification_tokens_token_hash_format",
        ),
        sa.CheckConstraint(
            "consumed_at IS NULL OR consumed_at >= created_at",
            name="ck_user_email_verification_tokens_consumption_after_creation",
        ),
        sa.CheckConstraint(
            "expires_at > created_at",
            name="ck_user_email_verification_tokens_expiry_after_creation",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "token_hash", name="uq_user_email_verification_tokens_token_hash"
        ),
    )
    op.create_index(
        op.f("ix_user_email_verification_tokens_expires_at"),
        "user_email_verification_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_email_verification_tokens_user_id"),
        "user_email_verification_tokens",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_email_verification_tokens_user_id"),
        table_name="user_email_verification_tokens",
    )
    op.drop_index(
        op.f("ix_user_email_verification_tokens_expires_at"),
        table_name="user_email_verification_tokens",
    )
    op.drop_table("user_email_verification_tokens")
    # ### end Alembic commands ###
