"""create document processing jobs table

Revision ID: 35cdd6cb56d4
Revises: 3e9722db5274
Create Date: 2026-08-22 20:53:35.219954

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35cdd6cb56d4"
down_revision: Union[str, Sequence[str], None] = "3e9722db5274"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_processing_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="queued", nullable=False
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'completed', 'failed')",
            name="ck_document_processing_jobs_status",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name="ck_document_processing_jobs_attempt_count_nonnegative",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_version_id",
            name="uq_document_processing_jobs_document_version_id",
        ),
    )
    op.create_index(
        op.f("ix_document_processing_jobs_document_version_id"),
        "document_processing_jobs",
        ["document_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_processing_jobs_status"),
        "document_processing_jobs",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_processing_jobs_status"),
        table_name="document_processing_jobs",
    )
    op.drop_index(
        op.f("ix_document_processing_jobs_document_version_id"),
        table_name="document_processing_jobs",
    )
    op.drop_table("document_processing_jobs")
    # ### end Alembic commands ###
