"""create document pages table

Revision ID: 3e9722db5274
Revises: 1aee65169b74
Create Date: 2026-08-22 19:47:13.511955

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e9722db5274"
down_revision: Union[str, Sequence[str], None] = "1aee65169b74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_pages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "page_number > 0", name="ck_document_pages_page_number_positive"
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_version_id",
            "page_number",
            name="uq_document_pages_document_version_id_page_number",
        ),
    )
    op.create_index(
        op.f("ix_document_pages_document_version_id"),
        "document_pages",
        ["document_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_pages_document_version_id"), table_name="document_pages"
    )
    op.drop_table("document_pages")
    # ### end Alembic commands ###
