"""create document chunks table

Revision ID: 4b1b119fa8ab
Revises: 35cdd6cb56d4
Create Date: 2026-08-25 19:10:11.523724

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b1b119fa8ab"
down_revision: Union[str, Sequence[str], None] = "35cdd6cb56d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_page_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chunk_index >= 0", name="ck_document_chunks_chunk_index_nonnegative"
        ),
        sa.CheckConstraint(
            "end_offset > start_offset", name="ck_document_chunks_offsets_valid"
        ),
        sa.CheckConstraint(
            "start_offset >= 0", name="ck_document_chunks_start_offset_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["document_page_id"], ["document_pages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_page_id",
            "chunk_index",
            name="uq_document_chunks_document_page_id_chunk_index",
        ),
    )
    op.create_index(
        op.f("ix_document_chunks_document_page_id"),
        "document_chunks",
        ["document_page_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_chunks_document_page_id"), table_name="document_chunks"
    )
    op.drop_table("document_chunks")
    # ### end Alembic commands ###
