"""add email verification state to users

Revision ID: 7a595c22ee85
Revises: b1f4ac5d558f
Create Date: 2026-09-07 08:50:12.581013

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a595c22ee85"
down_revision: Union[str, Sequence[str], None] = "b1f4ac5d558f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "users",
        sa.Column(
            "email_verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.execute(
        sa.text(
            """
            UPDATE users
            SET email_verified_at = created_at
            WHERE email_verified_at IS NULL
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified_at")
    # ### end Alembic commands ###
