"""create decision audit events table

Revision ID: 8f054eb0a48b
Revises: aa0726b6a77f
Create Date: 2026-08-28 10:12:33.086936

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8f054eb0a48b"
down_revision: Union[str, Sequence[str], None] = "aa0726b6a77f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column(
            "event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('decision_created', 'alternative_added', 'alternative_updated', 'alternative_removed', 'evidence_added', 'evidence_removed', 'decision_submitted', 'decision_finalized', 'decision_cancelled', 'decision_superseded')",
            name="ck_decision_audit_events_type",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(event_data) = 'object'",
            name="ck_decision_audit_events_data_object",
        ),
        sa.CheckConstraint(
            "sequence_number > 0", name="ck_decision_audit_events_sequence_positive"
        ),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "decision_id",
            "sequence_number",
            name="uq_decision_audit_events_decision_sequence",
        ),
    )
    op.create_index(
        op.f("ix_decision_audit_events_decision_id"),
        "decision_audit_events",
        ["decision_id"],
        unique=False,
    )

    op.execute(
        """
        CREATE FUNCTION prevent_decision_audit_event_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'decision audit events are immutable'
                USING ERRCODE = '55000';

            RETURN OLD;
        END;
        $$;
        """
    )

    op.execute(
        """
        CREATE TRIGGER trg_decision_audit_events_immutable
        BEFORE UPDATE OR DELETE ON decision_audit_events
        FOR EACH ROW
        EXECUTE FUNCTION prevent_decision_audit_event_mutation();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP TRIGGER trg_decision_audit_events_immutable
        ON decision_audit_events;
        """
    )

    op.execute(
        """
        DROP FUNCTION prevent_decision_audit_event_mutation();
        """
    )
    op.drop_index(
        op.f("ix_decision_audit_events_decision_id"), table_name="decision_audit_events"
    )
    op.drop_table("decision_audit_events")
    # ### end Alembic commands ###
