"""add decision audit actor attribution

Revision ID: 940b0fb71c87
Revises: d59fb6a7123e
Create Date: 2026-09-27 20:04:59.774026

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "940b0fb71c87"
down_revision: Union[str, Sequence[str], None] = "d59fb6a7123e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "decision_audit_events", sa.Column("actor_user_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_decision_audit_events_actor_user_id"),
        "decision_audit_events",
        ["actor_user_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_decision_audit_events_actor_user_id_users",
        "decision_audit_events",
        "users",
        ["actor_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_decision_audit_events_actor_user_id_users",
        "decision_audit_events",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_decision_audit_events_actor_user_id"),
        table_name="decision_audit_events",
    )
    op.drop_column("decision_audit_events", "actor_user_id")
    # ### end Alembic commands ###
