"""add processing job retry schedule

Revision ID: 969caa19289b
Revises: 2e13da26c190
Create Date: 2026-08-27 12:01:37.723101

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "969caa19289b"
down_revision: Union[str, Sequence[str], None] = "2e13da26c190"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_processing_jobs",
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_document_processing_jobs_next_attempt_at"),
        "document_processing_jobs",
        ["next_attempt_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_processing_jobs_next_attempt_at"),
        table_name="document_processing_jobs",
    )
    op.drop_column("document_processing_jobs", "next_attempt_at")
    # ### end Alembic commands ###
