"""add decision review outcome fields

Revision ID: aa0726b6a77f
Revises: 00d0041de8d2
Create Date: 2026-08-28 01:09:28.844780

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa0726b6a77f"
down_revision: Union[str, Sequence[str], None] = "00d0041de8d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "decisions", sa.Column("selected_alternative_id", sa.Uuid(), nullable=True)
    )
    op.add_column("decisions", sa.Column("rationale", sa.Text(), nullable=True))
    op.add_column(
        "decisions",
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "decisions", sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "decisions",
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "decisions",
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_decisions_selected_alternative_id"),
        "decisions",
        ["selected_alternative_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_decisions_selected_alternative_id",
        "decisions",
        "decision_alternatives",
        ["selected_alternative_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_decisions_selected_alternative_id", "decisions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_decisions_selected_alternative_id"), table_name="decisions")
    op.drop_column("decisions", "superseded_at")
    op.drop_column("decisions", "cancelled_at")
    op.drop_column("decisions", "decided_at")
    op.drop_column("decisions", "submitted_at")
    op.drop_column("decisions", "rationale")
    op.drop_column("decisions", "selected_alternative_id")
    # ### end Alembic commands ###
