"""add document status constraint

Revision ID: cb114c246669
Revises: b2c72fcbe3fb
Create Date: 2026-08-17 22:51:32.663477

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb114c246669"
down_revision: Union[str, Sequence[str], None] = "b2c72fcbe3fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_documents_status",
        "documents",
        "status IN ('pending', 'processing', 'ready', 'failed', 'archived')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_documents_status", "documents", type_="check")
    # ### end Alembic commands ###
